export type Technique='POOR'|'OK'|'GOOD'|'EXCELLENT';
export type SessionStatus='IN_PROGRESS'|'COMPLETED'|'PARTIAL'|'ABANDONED';
export type BlockType='STRAIGHT_SET'|'EMOM'|'BAR_SET'|'DENSITY'|'TEST'|'RECOVERY'|'ASSISTED_ENDURANCE';
export type Action='MAINTAIN'|'INCREASE_REPS'|'INCREASE_SETS'|'REDUCE_REST'|'INCREASE_DENSITY'|'INCREASE_DURATION'|'PROGRESS_VARIANT'|'REGRESS_VARIANT'|'REDUCE_ASSISTANCE'|'DELOAD';
export type Strategy='REPS_THEN_VOLUME'|'REPS_THEN_DURATION'|'ROUNDS_THEN_REST'|'PERFORMANCE_THEN_DENSITY'|'ASSISTANCE_THEN_REPS';
export interface Performance {date:string; targetReps:number; actualReps:number; rir:number; technique:Technique; completed:boolean; exercise:string; setNumber:number; targetId:string; rest:number; sessionId?:string; blockType?:BlockType; progressionKey?:string; assistanceLevel?:'HEAVY'|'MEDIUM'|'LIGHT'|'MINIMAL'; assistanceRank?:number;}
export interface ExerciseTarget {id:string; exercise:string; variant:string; sets:number; reps:number; minReps:number; maxReps:number; rir:number; rest:number; strategy:Strategy; source:'PROGRAM'|'ENGINE_ACCEPTED'|'USER_KEEP'|'USER_OVERRIDE'; progressionKey?:string; assistanceLevel?:'HEAVY'|'MEDIUM'|'LIGHT'|'MINIMAL'; assistanceRank?:number; type?:BlockType; duration?:number; rounds?:number; sequence?:string[]; progressionVariant?:string; regressionVariant?:string; maxSets?:number; minRest?:number; maxDuration?:number; maxRounds?:number;}
export interface Workout {id:string; name:string; day:string; block:string; week:number; duration:number; targets:ExerciseTarget[]; type?:BlockType;}
export interface ProgramCycle {id:string; programId:string; startedAt:string; currentWeek:number; currentBlock:'A'|'B'|'DELOAD'|'C'|'P'; status:'ACTIVE'|'COMPLETED'|'PAUSED'; completedWeeks:number[]; createdAt:string;}
export interface DecisionEvidence {exposures:number; strongExposures:number; badExposures:number; consecutiveStrong:number; lastCompletion:number; lastRepsRatio:number; avgRir:number; minTechnique:Technique|'—'; recentDates:string[]; criteria:string[];}
export interface Decision {exercise:string; action:Action; current:number; next:number; reason:string; confidence:'LOW'|'MEDIUM'|'HIGH'; date:string; accepted?:boolean; source?:'ENGINE'|'USER_KEEP'|'USER_OVERRIDE'; nextSets?:number; nextRest?:number; nextDuration?:number; nextRounds?:number; nextVariant?:string; nextAssistanceLevel?:'HEAVY'|'MEDIUM'|'LIGHT'|'MINIMAL'; currentAssistanceLevel?:'HEAVY'|'MEDIUM'|'LIGHT'|'MINIMAL'; evidence?:DecisionEvidence;}
export interface TestLog {targetId:string; values:Record<string,number>;}
export interface DensityLog {targetId:string; duration:number; rounds:number; totalReps:number;}
export interface Session {id:string; workoutId:string; startedAt:string; endedAt?:string; status:SessionStatus; performances:Performance[]; emom?:EmomLog[]; barSet?:BarSetLog; density?:DensityLog[]; tests?:TestLog[]; totalDuration?:number; targetSnapshot?:ExerciseTarget[]; currentTargetIndex?:number; currentSetNumber?:number; emomMinute?:number; emomStartAt?:number|null; emomLogged?:boolean; emomInterruptedAt?:string; emomUnverifiedMinutes?:number[]; barRound?:number; barRoundStartAt?:number|null; barFailedReps?:string; restEndAt?:number|null; skippedTargetIds?:string[];}
export interface EmomLog {targetId:string; exercise:string; minutes:number; targetReps:number; actualReps:number[]; rir:number[]; technique:Technique[]; sessionId?:string; blockType?:BlockType; progressionKey?:string; assistanceLevel?:'HEAVY'|'MEDIUM'|'LIGHT'|'MINIMAL'; assistanceRank?:number;}
export interface BarSetRound {round:number; startedAt:string; endedAt?:string; elapsed?:number; failedReps:number; technique:Technique;}
export interface BarSetLog {targetId:string; roundsPlanned:number; roundsCompleted:number; totalTime?:number; restBetweenRounds:number; failedReps:number; technique:Technique; rounds:BarSetRound[];}
